### ISSUE TITLE
显示屏突然无背光

### ISSUE THREAD

**Issue by moqi2011** [Corazon0513/Y9000X-2020-i9-Hackintosh#1]
开机过后，过几分钟显示器会变的很暗。然后又过几分钟，又恢复正常。
在安装的时候就这样的，安装完成过后也是这样的。
其它功能都是正常的，是什么原因导致的呢？

**Comment by Corazon0513** [comment]
> 开机过后，过几分钟显示器会变的很暗。然后又过几分钟，又恢复正常。
> 
> 在安装的时候就这样的，安装完成过后也是这样的。
> 
> 其它功能都是正常的，是什么原因导致的呢？

是否正确填写三码与机型？

**Comment by moqi2011** [comment]
确实是因为没有填写三码和机型导致的，正确填入后就可以了。谢谢
